<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        $rombelId = 1; // Kelas 1 - Apel

        $students = [
            [
                'nama_lengkap'   => 'AFIF PUTRA RAMADHAN',
                'nama_panggilan' => 'AFIF',
                'nipd'           => '1130',
                'nisn'           => '3189211023',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2018-08-06',
                'alamat'         => 'Jl. MANGUNDARMO RT. 35 RW. 03 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => 'Slamet',
                'kecamatan'      => 'Tumpang',
                'kode_pos'       => '65156',
                'nama_ayah'      => 'AHMAD ZAINUL',
                'nama_ibu'       => 'ISTIANI',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'AKHTARI BIMANTARA',
                'nama_panggilan' => 'BIMA',
                'nipd'           => '1131',
                'nisn'           => '3187763857',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2018-10-24',
                'alamat'         => 'Jl. RAYA BELUNG UTARA RT. 01 RW. 01 DESA BELUNG KEC. PONCOKUSUMO',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'CHORI WAHYU SETYA',
                'nama_ibu'       => 'MINA TOYIBATUL',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'ALMIRA AHZARA',
                'nama_panggilan' => 'ALMIRA',
                'nipd'           => '1132',
                'nisn'           => '3189639338',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2018-03-07',
                'alamat'         => 'Jl. RAYA BELUNG RT. 01 RW. 01 DESA BELUNG KEC. PONCOKUSUMO',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'KHOIRUL MUSTAIN',
                'nama_ibu'       => 'RIANAH',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'ANNASYA KEYLA AURISKA',
                'nama_panggilan' => 'KEYLA',
                'nipd'           => '1133',
                'nisn'           => '3190167469',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'PASURUAN',
                'tanggal_lahir'  => '2019-12-01',
                'alamat'         => 'Jl. MANGUNDARMO RT. 35 RW. 03 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'SIGIT ILONAH',
                'nama_ibu'       => 'IRMA ANDRIANI NINGSIH',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'AQILA DEVIANA AL ZAHRA',
                'nama_panggilan' => 'AQILA',
                'nipd'           => '1134',
                'nisn'           => '3194629363',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2019-01-14',
                'alamat'         => 'Jl. MPU BARADA RT. 22 RW. 02 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'HARIANTO',
                'nama_ibu'       => 'CICIK RAHAYU',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'ARISTA ADINDA ZAHRANY',
                'nama_panggilan' => 'ARISTA',
                'nipd'           => '1135',
                'nisn'           => '3185710853',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2018-08-06',
                'alamat'         => 'DUSUN PRAPATAN RT. 37 RW. 04 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'MUHAMMAD AGUS ARIF',
                'nama_ibu'       => 'RENNY FITRIA',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'ARYAN ZARIF DANIEL PAMBUDI',
                'nama_panggilan' => 'DANIEL',
                'nipd'           => '1136',
                'nisn'           => '3180172906',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2018-09-13',
                'alamat'         => 'Jl. MANGUNDARMO RT. 34 RW. 03 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'DIAN RISKI BUDIANTO',
                'nama_ibu'       => 'KUSNIATUL WACHIDAH',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'FATHAN MAULANA ALFARIQ',
                'nama_panggilan' => 'FATHAN',
                'nipd'           => '1137',
                'nisn'           => '3181735690',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2018-10-07',
                'alamat'         => 'Jl. RAYA PRAPATAN TULUSAYU RT. 39 RW. 05 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'SUKARMAT',
                'nama_ibu'       => 'SUSI WAHYUNI',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'KHANSA SHAQEENA ALMAHYRA',
                'nama_panggilan' => 'KHANSA',
                'nipd'           => '1138',
                'nisn'           => '3171326098',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2017-04-04',
                'alamat'         => 'Jl. MANGUNDARMO DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'MUHAMMAD SULIADI',
                'nama_ibu'       => 'RIRIN KHOIRIYAH',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'MOHAMMAD ARKA HAIDAR RISYAD',
                'nama_panggilan' => 'ARKA',
                'nipd'           => '1139',
                'nisn'           => '3182693441',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2018-06-12',
                'alamat'         => 'Jl. MPU BARADA RT. 22 RW. 02 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'JUMAKIR',
                'nama_ibu'       => 'SELA AYUNINGTYAS',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'MUHAMMAD SABILILLAH FAHRI RAMADHAN',
                'nama_panggilan' => 'SABIL',
                'nipd'           => '1140',
                'nisn'           => '3183158140',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'JEMBER',
                'tanggal_lahir'  => '2018-05-28',
                'alamat'         => 'DUSUN PRAPATAN RT. 36 RW. 04 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'MOH. SOLIHIN',
                'nama_ibu'       => 'IRAWATI CANDRA DEWI',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'NUR FALISHA',
                'nama_panggilan' => 'FALISHA',
                'nipd'           => '1141',
                'nisn'           => '3188839411',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'GORONTALO',
                'tanggal_lahir'  => '2018-01-05',
                'alamat'         => 'DUSUN PRAPATAN RT. 37 RW. 04 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => null,
                'nama_ibu'       => 'LUN H. NTUU',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'RAFFA AZKA ALFARIDZI',
                'nama_panggilan' => 'RAFA',
                'nipd'           => '1142',
                'nisn'           => '3197270680',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'L',
                'tempat_lahir'   => 'MALANG',
                'tanggal_lahir'  => '2019-03-23',
                'alamat'         => 'Jl. MANGUNDARMO GG. I RT.32 RW. 03 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'DIDIK SULISTYANTO',
                'nama_ibu'       => 'INDRAWATI',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
            [
                'nama_lengkap'   => 'SAFINA TUNNAJAH',
                'nama_panggilan' => 'SAFINA',
                'nipd'           => '1143',
                'nisn'           => '3175598821',
                'agama'          => 'Islam',
                'jenis_kelamin'  => 'P',
                'tempat_lahir'   => 'SURABAYA',
                'tanggal_lahir'  => '2017-03-14',
                'alamat'         => 'Jl. MPU GANDRING RT. 18 RW. 01 DESA TULUSBESAR KEC. TUMPANG',
                'rt'             => null,
                'rw'             => null,
                'desa_kelurahan' => null,
                'kecamatan'      => null,
                'kode_pos'       => '65156',
                'nama_ayah'      => 'SUPRIYANTO',
                'nama_ibu'       => 'NURHAYATI',
                'pekerjaan_ayah' => null,
                'pekerjaan_ibu'  => null,
                'rombel_id'      => $rombelId,
            ],
        ];

        foreach ($students as $data) {
            Student::updateOrCreate(['nipd' => $data['nipd']], $data);
        }
    }
}